# Generated by Duan Level 6 - No-space tokenization + Pure indentation
# 调试模式：设为 真 可输出异常处理核心分支的详细日志
调试模式 = 假

def 日志(msg):
    if 调试模式:
        打印("[DEBUG]", msg)

def 转字符串(v):
    return str(v)

def 关键字列表():
    return 列表创建("设", "段落", "段", "返回", "为", "如果", "否则", "当", "接收", "加", "减", "乘", "除", "取模", "等于", "小于", "大于", "小于等于", "大于等于", "不等于", "且", "或", "非", "遍历", "在", "类", "属性", "己", "继承", "父", "尝试", "捕获", "最终", "抛出", "导入", "导出", "开启类型检查", "关闭类型检查")

def 是关键字(w):
    kws = 关键字列表()
    i = 0
    while i < 列表长度(kws):
        if 列表获取(kws, i) == w:
            return 真
        i = i + 1
    return 假

def 是函数关键字(w):
    if w == "段落":
        return 真
    if w == "段":
        return 真
    return 假

def 建(t, v):
    return 列表创建(t, v)

def 列表弹栈(lst):
    if 列表长度(lst) > 0:
        lst.pop()

def 是类型名(name):
    return name in ("整数", "文本", "小数", "布尔", "空", "列表", "字典")

def 类型名到Python(tname):
    if tname == "整数":
        return "int"
    if tname == "文本":
        return "str"
    if tname == "小数":
        return "float"
    if tname == "布尔":
        return "bool"
    if tname == "空":
        return "None"
    if tname == "列表":
        return "list"
    if tname == "字典":
        return "dict"
    return tname

def 解析类型(toks, p):
    """解析类型表达式，返回 (类型字符串, 新位置)。支持复合类型如 列表[整数]、字典[文本, 整数]"""
    if p >= 列表长度(toks):
        return 列表创建("", p)
    tok = 列表获取(toks, p)
    if 列表获取(tok, 0) != "ID":
        return 列表创建("", p)
    type_name = 列表获取(tok, 1)
    if not 是类型名(type_name):
        return 列表创建("", p)
    type_str = 类型名到Python(type_name)
    p = p + 1
    # 检查泛型参数: 列表[整数]
    if p < 列表长度(toks):
        ntok = 列表获取(toks, p)
        if 列表获取(ntok, 0) == "LBRACKET":
            type_str += "["
            p = p + 1
            first = 真
            while p < 列表长度(toks):
                ntok = 列表获取(toks, p)
                if 列表获取(ntok, 0) == "RBRACKET":
                    type_str += "]"
                    p = p + 1
                    break
                if not first:
                    if 列表获取(ntok, 0) == "COMMA":
                        type_str += ", "
                        p = p + 1
                        continue
                first = 假
                elem_result = 解析类型(toks, p)
                elem_type = 列表获取(elem_result, 0)
                if elem_type == "":
                    break
                type_str += elem_type
                p = 列表获取(elem_result, 1)
    return 列表创建(type_str, p)

def 生成类型检查代码(var_name, py_type, indent):
    """生成运行时类型检查代码"""
    indent_str = "    " * indent
    return indent_str + "if 类型检查开启:\n" + indent_str + "    if not isinstance(" + var_name + ", " + py_type + "):\n" + indent_str + "        raise TypeError(f\"期望 " + py_type + ", 实际 {type(" + var_name + ")}\")\n"

def 数字(src, p, n, s):
    while p < n:
        c = 字符串获取(src, p)
        if c >= "0" and c <= "9":
            s = s + c
            p = p + 1
        else:
            return 建("NUM", s)
    return 建("NUM", s)

def 字符串(src, p, n, s):
    while p < n:
        c = 字符串获取(src, p)
        if c == "\"":
            tok = 建("STR", s)
            return 列表创建(tok, p + 1)
        s = s + c
        p = p + 1
    tok = 建("STR", s)
    return 列表创建(tok, p)

def 扫注释(src, p, n):
    while p < n:
        c = 字符串获取(src, p)
        if c == "\n":
            return p + 1
        p = p + 1
    return p

def 最长匹配(src, p, n):
    """从位置p开始，尝试匹配最长关键字"""
    kws = 关键字列表()
    best_kw = ""
    best_len = 0
    for kw in kws:
        kw_len = 字符串长度(kw)
        if kw_len <= n - p:
            match = 真
            for i in range(kw_len):
                if 字符串获取(src, p + i) != 字符串获取(kw, i):
                    match = 假
                    break
            if match and kw_len > best_len:
                best_kw = kw
                best_len = kw_len
    if best_len > 0:
        return 建("KW", best_kw), best_len
    return None, 0

def 扫(src, p, n, toks):
    缩进栈 = 列表创建(0)
    while p < n:
        # ====== 行首缩进处理 ======
        indent = 0
        while p < n and 字符串获取(src, p) == " ":
            indent = indent + 1
            p = p + 1
        if p >= n:
            break
        c = 字符串获取(src, p)
        if c == "\n":
            p = p + 1
            continue
        if c == "#":
            p = 扫注释(src, p + 1, n)
            continue
        top = 列表获取(缩进栈, 列表长度(缩进栈) - 1)
        if indent > top:
            日志("INDENT indent=" + 转字符串(indent) + " top=" + 转字符串(top))
            列表追加(toks, 建("INDENT", indent))
            列表追加(缩进栈, indent)
        elif indent < top:
            日志("DEDENT indent=" + 转字符串(indent) + " top=" + 转字符串(top))
            while indent < 列表获取(缩进栈, 列表长度(缩进栈) - 1):
                列表追加(toks, 建("DEDENT", 列表获取(缩进栈, 列表长度(缩进栈) - 1)))
                列表弹栈(缩进栈)
        # ====== 行内内容处理 ======
        while p < n:
            c = 字符串获取(src, p)
            已处理 = 假
            if c == " ":
                p = p + 1
                已处理 = 真
            if 已处理 == 假 and c == "\n":
                列表追加(toks, 建("NEWLINE", "\n"))
                p = p + 1
                break
            if 已处理 == 假 and c == "#":
                p = 扫注释(src, p + 1, n)
                break
            if 已处理 == 假 and c == "'":
                if p + 1 < n:
                    nc = 字符串获取(src, p + 1)
                    if nc == "\"":
                        列表追加(toks, 建("STR", "\""))
                        p = p + 3
                        已处理 = 真
                if 已处理 == 假:
                    # 读取单引号字符串
                    sp = p + 1
                    s = ""
                    while sp < n:
                        sc = 字符串获取(src, sp)
                        if sc == "'":
                            tok = 建("STR", s)
                            列表追加(toks, tok)
                            p = sp + 1
                            已处理 = 真
                            break
                        s = s + sc
                        sp = sp + 1
                    if 已处理 == 假:
                        tok = 建("STR", s)
                        列表追加(toks, tok)
                        p = sp
                        已处理 = 真
            if 已处理 == 假 and c == "\"":
                if p + 1 < n:
                    nc = 字符串获取(src, p + 1)
                    if nc == "'":
                        列表追加(toks, 建("STR", "'"))
                        p = p + 3
                        已处理 = 真
                if 已处理 == 假:
                    结果 = 字符串(src, p + 1, n, "")
                    tok = 列表获取(结果, 0)
                    p = 列表获取(结果, 1)
                    列表追加(toks, tok)
                    已处理 = 真
            if 已处理 == 假 and c == "：":
                p = p + 1
                已处理 = 真
            if 已处理 == 假 and c == "。":
                p = p + 1
                已处理 = 真
            if 已处理 == 假 and c == "，":
                p = p + 1
                已处理 = 真
            if 已处理 == 假 and c == "(":
                列表追加(toks, 建("LPAREN", "("))
                p = p + 1
                已处理 = 真
            if 已处理 == 假 and c == ")":
                列表追加(toks, 建("RPAREN", ")"))
                p = p + 1
                已处理 = 真
            if 已处理 == 假 and c == "[":
                列表追加(toks, 建("LBRACKET", "["))
                p = p + 1
                已处理 = 真
            if 已处理 == 假 and c == "]":
                列表追加(toks, 建("RBRACKET", "]"))
                p = p + 1
                已处理 = 真
            if 已处理 == 假 and c == ",":
                列表追加(toks, 建("COMMA", ","))
                p = p + 1
                已处理 = 真
            if 已处理 == 假 and c == ".":
                列表追加(toks, 建("DOT", "."))
                p = p + 1
                已处理 = 真
            if 已处理 == 假 and c == "=":
                列表追加(toks, 建("EQ", "="))
                p = p + 1
                已处理 = 真
            if 已处理 == 假 and c >= "0" and c <= "9":
                tok = 数字(src, p, n, "")
                列表追加(toks, tok)
                p = p + 字符串长度(列表获取(tok, 1))
                已处理 = 真
            if 已处理 == 假 and c == "-":
                if p + 1 < n:
                    nc = 字符串获取(src, p + 1)
                    if nc >= "0" and nc <= "9":
                        tok = 数字(src, p + 1, n, "-")
                        列表追加(toks, tok)
                        p = p + 字符串长度(列表获取(tok, 1))
                        已处理 = 真
            if 已处理 == 假:
                # 尝试最长关键字匹配
                结果, 匹配长度 = 最长匹配(src, p, n)
                if 结果 is not None:
                    列表追加(toks, 结果)
                    p = p + 匹配长度
                    已处理 = 真
            if 已处理 == 假:
                # 读取标识符，同时检查关键字匹配
                是字母 = c == "_" or (c >= "a" and c <= "z") or (c >= "A" and c <= "Z") or (c >= "\u4e00" and c <= "\u9fff")
                if 是字母:
                    word = ""
                    while p < n:
                        c = 字符串获取(src, p)
                        is_letter = c == "_" or (c >= "a" and c <= "z") or (c >= "A" and c <= "Z") or (c >= "\u4e00" and c <= "\u9fff")
                        if not is_letter:
                            break
                        # 检查从当前位置开始是否能匹配到关键字
                        kw_result, kw_len = 最长匹配(src, p, n)
                        if kw_result is not None and kw_len > 0:
                            if word != "":
                                列表追加(toks, 建("ID", word))
                            列表追加(toks, kw_result)
                            p = p + kw_len
                            word = ""
                            continue
                        word = word + c
                        p = p + 1
                    if word != "":
                        列表追加(toks, 建("ID", word))
                    已处理 = 真
            if 已处理 == 假:
                p = p + 1
    # 文件末尾，生成 DEDENT 直到回到缩进0
    while 列表长度(缩进栈) > 1:
        列表追加(toks, 建("DEDENT", 列表获取(缩进栈, 列表长度(缩进栈) - 1)))
        列表弹栈(缩进栈)
    return toks

def 词法(src):
    return 扫(src, 0, 字符串长度(src), 列表创建())

def 表达式(toks, p):
    return 或表达式(toks, p)

def 或表达式(toks, p):
    结果 = 且表达式(toks, p)
    left = 列表获取(结果, 0)
    np = 列表获取(结果, 1)
    继续循环 = 真
    while 继续循环 and np < 列表长度(toks):
        tok = 列表获取(toks, np)
        tv = 列表获取(tok, 1)
        if tv != "或":
            继续循环 = 假
        else:
            右结果 = 且表达式(toks, np + 1)
            right = 列表获取(右结果, 0)
            np = 列表获取(右结果, 1)
            left = left + " or " + right
    return 列表创建(left, np)

def 且表达式(toks, p):
    结果 = 比较表达式(toks, p)
    left = 列表获取(结果, 0)
    np = 列表获取(结果, 1)
    继续循环 = 真
    while 继续循环 and np < 列表长度(toks):
        tok = 列表获取(toks, np)
        tv = 列表获取(tok, 1)
        if tv != "且":
            继续循环 = 假
        else:
            右结果 = 比较表达式(toks, np + 1)
            right = 列表获取(右结果, 0)
            np = 列表获取(右结果, 1)
            left = left + " and " + right
    return 列表创建(left, np)

def 比较表达式(toks, p):
    结果 = 加减表达式(toks, p)
    left = 列表获取(结果, 0)
    np = 列表获取(结果, 1)
    if np < 列表长度(toks):
        tok = 列表获取(toks, np)
        tv = 列表获取(tok, 1)
        if tv == "等于":
            右结果 = 加减表达式(toks, np + 1)
            right = 列表获取(右结果, 0)
            np = 列表获取(右结果, 1)
            return 列表创建(left + " == " + right, np)
        if tv == "小于":
            右结果 = 加减表达式(toks, np + 1)
            right = 列表获取(右结果, 0)
            np = 列表获取(右结果, 1)
            return 列表创建(left + " < " + right, np)
        if tv == "大于":
            右结果 = 加减表达式(toks, np + 1)
            right = 列表获取(右结果, 0)
            np = 列表获取(右结果, 1)
            return 列表创建(left + " > " + right, np)
        if tv == "小于等于":
            右结果 = 加减表达式(toks, np + 1)
            right = 列表获取(右结果, 0)
            np = 列表获取(右结果, 1)
            return 列表创建(left + " <= " + right, np)
        if tv == "大于等于":
            右结果 = 加减表达式(toks, np + 1)
            right = 列表获取(右结果, 0)
            np = 列表获取(右结果, 1)
            return 列表创建(left + " >= " + right, np)
        if tv == "不等于":
            右结果 = 加减表达式(toks, np + 1)
            right = 列表获取(右结果, 0)
            np = 列表获取(右结果, 1)
            return 列表创建(left + " != " + right, np)
    return 列表创建(left, np)

def 加减表达式(toks, p):
    结果 = 乘除表达式(toks, p)
    left = 列表获取(结果, 0)
    np = 列表获取(结果, 1)
    继续循环 = 真
    while 继续循环 and np < 列表长度(toks):
        tok = 列表获取(toks, np)
        tv = 列表获取(tok, 1)
        if tv == "加":
            右结果 = 乘除表达式(toks, np + 1)
            right = 列表获取(右结果, 0)
            np = 列表获取(右结果, 1)
            left = left + " + " + right
        else:
            if tv == "减":
                右结果 = 乘除表达式(toks, np + 1)
                right = 列表获取(右结果, 0)
                np = 列表获取(右结果, 1)
                left = left + " - " + right
            else:
                继续循环 = 假
    return 列表创建(left, np)

def 乘除表达式(toks, p):
    结果 = 成员表达式(toks, p)
    left = 列表获取(结果, 0)
    np = 列表获取(结果, 1)
    继续循环 = 真
    while 继续循环 and np < 列表长度(toks):
        tok = 列表获取(toks, np)
        tv = 列表获取(tok, 1)
        if tv == "乘":
            右结果 = 成员表达式(toks, np + 1)
            right = 列表获取(右结果, 0)
            np = 列表获取(右结果, 1)
            left = left + " * " + right
        else:
            if tv == "除":
                右结果 = 成员表达式(toks, np + 1)
                right = 列表获取(右结果, 0)
                np = 列表获取(右结果, 1)
                left = left + " // " + right
            else:
                if tv == "取模":
                    右结果 = 成员表达式(toks, np + 1)
                    right = 列表获取(右结果, 0)
                    np = 列表获取(右结果, 1)
                    left = left + " % " + right
                else:
                    继续循环 = 假
    return 列表创建(left, np)

def 成员表达式(toks, p):
    结果 = 一元表达式(toks, p)
    left = 列表获取(结果, 0)
    np = 列表获取(结果, 1)
    return 处理成员链(toks, np, left)

def 处理成员链(toks, p, left):
    np = p
    while np < 列表长度(toks):
        dot_tok = 列表获取(toks, np)
        if 列表获取(dot_tok, 0) == "DOT":
            np = np + 1
            if np < 列表长度(toks):
                attr_tok = 列表获取(toks, np)
                attr_name = 列表获取(attr_tok, 1)
                np = np + 1
                if np < 列表长度(toks):
                    next_tok = 列表获取(toks, np)
                    if 列表获取(next_tok, 0) == "LPAREN":
                        参数结果 = 解析参数列表(toks, np + 1)
                        args = 列表获取(参数结果, 0)
                        np = 列表获取(参数结果, 1)
                        left = left + "." + attr_name + "(" + args + ")"
                    else:
                        left = left + "." + attr_name
                else:
                    left = left + "." + attr_name
            else:
                return 列表创建(left, np)
        else:
            return 列表创建(left, np)
    return 列表创建(left, np)

def 一元表达式(toks, p):
    if p < 列表长度(toks):
        tok = 列表获取(toks, p)
        if 列表获取(tok, 0) == "KW" and 列表获取(tok, 1) == "非":
            结果 = 一元表达式(toks, p + 1)
            expr = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            return 列表创建("not " + expr, np)
        if 列表获取(tok, 0) == "KW" and 列表获取(tok, 1) == "己":
            return 处理成员链(toks, p + 1, "self")
        if 列表获取(tok, 0) == "KW" and 列表获取(tok, 1) == "父":
            return 处理成员链(toks, p + 1, "super()")
        if 列表获取(tok, 0) == "LPAREN":
            结果 = 表达式(toks, p + 1)
            expr = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            if np < 列表长度(toks):
                tok = 列表获取(toks, np)
                if 列表获取(tok, 0) == "RPAREN":
                    return 列表创建('(' + expr + ')', np + 1)
            return 列表创建('(' + expr + ')', np)
        if 列表获取(tok, 0) == "NUM":
            return 列表创建(列表获取(tok, 1), p + 1)
        if 列表获取(tok, 0) == "STR":
            s = 列表获取(tok, 1)
            有单引号 = 假
            i = 0
            while i < 字符串长度(s):
                if 字符串获取(s, i) == "'":
                    有单引号 = 真
                i = i + 1
            if 有单引号:
                return 列表创建("\"" + s + "\"", p + 1)
            return 列表创建("'" + s + "'", p + 1)
        if 列表获取(tok, 0) == "ID":
            name = 列表获取(tok, 1)
            np = p + 1
            if np < 列表长度(toks):
                tok = 列表获取(toks, np)
                if 列表获取(tok, 0) == "LPAREN":
                    参数结果 = 解析参数列表(toks, np + 1)
                    args = 列表获取(参数结果, 0)
                    np = 列表获取(参数结果, 1)
                    return 列表创建(name + "(" + args + ")", np)
            return 列表创建(name, np)
        if 列表获取(tok, 0) == "LBRACKET":
            # 列表字面量 [elem1, elem2, ...]
            np = p + 1
            elems = 列表创建()
            while np < 列表长度(toks):
                tok = 列表获取(toks, np)
                if 列表获取(tok, 0) == "RBRACKET":
                    elem_str = ""
                    i = 0
                    while i < 列表长度(elems):
                        if i > 0:
                            elem_str = elem_str + ", "
                        elem_str = elem_str + 列表获取(elems, i)
                        i = i + 1
                    return 列表创建("[" + elem_str + "]", np + 1)
                if 列表获取(tok, 0) == "COMMA":
                    np = np + 1
                    continue
                结果 = 表达式(toks, np)
                expr = 列表获取(结果, 0)
                np = 列表获取(结果, 1)
                列表追加(elems, expr)
            elem_str = ""
            i = 0
            while i < 列表长度(elems):
                if i > 0:
                    elem_str = elem_str + ", "
                elem_str = elem_str + 列表获取(elems, i)
                i = i + 1
            return 列表创建("[" + elem_str + "]", np)
    return 列表创建("None", p)

def 解析参数列表(toks, p):
    if p < 列表长度(toks):
        tok = 列表获取(toks, p)
        if 列表获取(tok, 0) == "RPAREN":
            return 列表创建("", p + 1)
        结果 = 表达式(toks, p)
        first = 列表获取(结果, 0)
        np = 列表获取(结果, 1)
        剩余结果 = 解析更多参数(toks, np, first)
        return 剩余结果
    return 列表创建("", p)

def 解析更多参数(toks, p, acc):
    while p < 列表长度(toks):
        tok = 列表获取(toks, p)
        if 列表获取(tok, 0) == "RPAREN":
            return 列表创建(acc, p + 1)
        if 列表获取(tok, 0) == "COMMA":
            结果 = 表达式(toks, p + 1)
            next_arg = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            acc = acc + ", " + next_arg
            p = np
        else:
            p = p + 1
    return 列表创建(acc, p)

def find_ret(toks, p):
    if p < 列表长度(toks):
        tok = 列表获取(toks, p)
        if 列表获取(tok, 1) == "返回":
            结果 = 表达式(toks, p + 1)
            expr = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            return 列表创建("return " + expr, np)
    return 列表创建("pass", p)

def find_end(toks, p):
    while p < 列表长度(toks):
        tok = 列表获取(toks, p)
        if 列表获取(tok, 0) == "DEDENT":
            return p + 1
        if 列表获取(tok, 0) == "KW":
            if 是函数关键字(列表获取(tok, 1)):
                return p
        p = p + 1
    return p

def find_next(toks, p):
    while p < 列表长度(toks):
        tok = 列表获取(toks, p)
        if 列表获取(tok, 0) == "KW":
            tv = 列表获取(tok, 1)
            if 是函数关键字(tv):
                return p
            if tv == "设":
                return p
            if tv == "如果":
                return p
            if tv == "返回":
                return p
        p = p + 1
    return p

def comp_set(toks, p):
    if p < 列表长度(toks):
        tok = 列表获取(toks, p)
        if 列表获取(tok, 1) == "设":
            np = p + 1
            if np < 列表长度(toks):
                first_tok = 列表获取(toks, np)
                if 列表获取(first_tok, 0) == "KW" and 列表获取(first_tok, 1) == "己":
                    var_expr = "self"
                    np = np + 1
                    继续循环 = 真
                    while 继续循环 == 真 and np < 列表长度(toks):
                        dot_tok = 列表获取(toks, np)
                        if 列表获取(dot_tok, 0) == "DOT":
                            np = np + 1
                            if np < 列表长度(toks):
                                attr_tok = 列表获取(toks, np)
                                attr_name = 列表获取(attr_tok, 1)
                                var_expr = var_expr + "." + attr_name
                                np = np + 1
                            else:
                                继续循环 = 假
                        else:
                            继续循环 = 假
                    if np < 列表长度(toks):
                        tok = 列表获取(toks, np)
                        if 列表获取(tok, 1) == "为":
                            np = np + 1
                            结果 = 表达式(toks, np)
                            expr = 列表获取(结果, 0)
                            np = 列表获取(结果, 1)
                            return 列表创建(var_expr + " = " + expr, np)
                    else:
                        var = 列表获取(first_tok, 1)
                        np = np + 1
                        if np < 列表长度(toks):
                            tok = 列表获取(toks, np)
                            if 列表获取(tok, 1) == "为":
                                np = np + 1
                                结果 = 表达式(toks, np)
                                expr = 列表获取(结果, 0)
                                np = 列表获取(结果, 1)
                                return 列表创建(var + " = " + expr, np)
                else:
                    var = 列表获取(first_tok, 1)
                    np = np + 1
                    if np < 列表长度(toks):
                        tok = 列表获取(toks, np)
                        if 列表获取(tok, 1) == "为":
                            np = np + 1
                            if np < 列表长度(toks):
                                # 检查是否为类型注解（支持复合类型）
                                type_result = 解析类型(toks, np)
                                py_type = 列表获取(type_result, 0)
                                if py_type != "":
                                    np = 列表获取(type_result, 1)
                                    if np < 列表长度(toks):
                                        assign_tok = 列表获取(toks, np)
                                        if 列表获取(assign_tok, 1) == "=":
                                            np = np + 1
                                            结果 = 表达式(toks, np)
                                            expr = 列表获取(结果, 0)
                                            np = 列表获取(结果, 1)
                                            return 列表创建(var + ": " + py_type + " = " + expr + "\n" + 生成类型检查代码(var, py_type, 0), np)
                                    return 列表创建(var + ": " + py_type + " = None\n" + 生成类型检查代码(var, py_type, 0), np)
                                else:
                                    结果 = 表达式(toks, np)
                                    expr = 列表获取(结果, 0)
                                    np = 列表获取(结果, 1)
                                    return 列表创建(var + " = " + expr, np)
            return 列表创建("", p + 1)
    return 列表创建("", p)

def comp_throw(toks, p):
    if p < 列表长度(toks):
        tok = 列表获取(toks, p)
        if 列表获取(tok, 1) == "抛出":
            结果 = 表达式(toks, p + 1)
            expr = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            if 字符串长度(expr) > 0:
                first = 字符串获取(expr, 0)
                if first == "'" or first == '"':
                    stmt = "raise Exception(" + expr + ")"
                else:
                    stmt = "raise " + expr
            else:
                stmt = "raise " + expr
            日志("comp_throw: expr=" + expr + " stmt=" + stmt)
            return 列表创建(stmt, np)
    return 列表创建("", p)

def 异常类型映射(name):
    if name == "异常":
        return "Exception"
    if name == "值错误":
        return "ValueError"
    if name == "类型错误":
        return "TypeError"
    if name == "键错误":
        return "KeyError"
    if name == "索引错误":
        return "IndexError"
    if name == "除零错误":
        return "ZeroDivisionError"
    if name == "属性错误":
        return "AttributeError"
    if name == "名称错误":
        return "NameError"
    if name == "文件错误":
        return "FileNotFoundError"
    if name == "运行错误":
        return "RuntimeError"
    if name == "停止迭代":
        return "StopIteration"
    return name

def comp_try(toks, p, indent):
    if p < 列表长度(toks):
        tok = 列表获取(toks, p)
        if 列表获取(tok, 1) == "尝试":
            日志("comp_try: 开始处理 try 结构, p=" + 转字符串(p) + " indent=" + indent)
            np = p + 1
            out = indent + "try:\n"
            # 跳过 NEWLINE
            if np < 列表长度(toks):
                nt = 列表获取(toks, np)
                if 列表获取(nt, 0) == "NEWLINE":
                    np = np + 1
            # 跳过 INDENT
            if np < 列表长度(toks):
                nt = 列表获取(toks, np)
                if 列表获取(nt, 0) == "INDENT":
                    np = np + 1
            # 扫描整个 try-catch-finally 结构
            catch_positions = 列表创建()
            finally_pos = 0
            try_end = 9999
            depth = 1
            scan_p = np
            while scan_p < 列表长度(toks):
                st = 列表获取(toks, scan_p)
                stt = 列表获取(st, 0)
                if stt == "INDENT":
                    depth = depth + 1
                    日志("comp_try扫描: scan_p=" + 转字符串(scan_p) + " INDENT depth=" + 转字符串(depth))
                if stt == "DEDENT":
                    depth = depth - 1
                    日志("comp_try扫描: scan_p=" + 转字符串(scan_p) + " DEDENT depth=" + 转字符串(depth))
                    if depth == 0:
                        # 检查 DEDENT 后是否为 捕获/最终
                        if scan_p + 1 < 列表长度(toks):
                            nt = 列表获取(toks, scan_p + 1)
                            if 列表获取(nt, 0) == "KW":
                                ntv = 列表获取(nt, 1)
                                if ntv == "捕获":
                                    日志("comp_try扫描: 发现捕获, 位置=" + 转字符串(scan_p + 1))
                                    列表追加(catch_positions, scan_p + 1)
                                    scan_p = scan_p + 2
                                    depth = 0
                                    continue
                                if ntv == "最终":
                                    日志("comp_try扫描: 发现最终, 位置=" + 转字符串(scan_p + 1))
                                    finally_pos = scan_p + 1
                                    scan_p = scan_p + 2
                                    depth = 0
                                    continue
                        日志("comp_try扫描: depth=0 无后续关键词, try_end=" + 转字符串(scan_p))
                        try_end = scan_p
                        break
                scan_p = scan_p + 1
            if try_end == 9999:
                日志("comp_try: 扫描未找到结束位置, 返回空")
                return 列表创建("", p + 1)
            日志("comp_try: 扫描完成, catch_positions=" + 转字符串(catch_positions) + " finally_pos=" + 转字符串(finally_pos) + " try_end=" + 转字符串(try_end))
            body_indent = indent + "    "
            # 确定 try 体结束位置
            try_body_end = np
            if 列表长度(catch_positions) > 0:
                try_body_end = 列表获取(catch_positions, 0)
                bcp = try_body_end - 1
                while bcp >= 0:
                    bt = 列表获取(toks, bcp)
                    if 列表获取(bt, 0) == "DEDENT":
                        try_body_end = bcp
                        break
                    bcp = bcp - 1
                日志("comp_try: try体结束位置=" + 转字符串(try_body_end) + " (有捕获)")
            elif finally_pos != 0:
                try_body_end = finally_pos
                bcp = try_body_end - 1
                while bcp >= 0:
                    bt = 列表获取(toks, bcp)
                    if 列表获取(bt, 0) == "DEDENT":
                        try_body_end = bcp
                        break
                    bcp = bcp - 1
                日志("comp_try: try体结束位置=" + 转字符串(try_body_end) + " (有最终)")
            else:
                try_body_end = try_end
                日志("comp_try: try体结束位置=" + 转字符串(try_body_end) + " (无捕获/最终)")
            try_result = compile_block(toks, np, try_body_end, body_indent, "")
            out = out + try_result
            # 处理每个捕获
            ci = 0
            while ci < 列表长度(catch_positions):
                cp = 列表获取(catch_positions, ci)
                日志("comp_try: 处理捕获 #" + 转字符串(ci) + " 位置=" + 转字符串(cp))
                catch_end = try_end
                if ci + 1 < 列表长度(catch_positions):
                    next_catch = 列表获取(catch_positions, ci + 1)
                    catch_end = next_catch
                    bcp = catch_end - 1
                    while bcp >= 0:
                        bt = 列表获取(toks, bcp)
                        if 列表获取(bt, 0) == "DEDENT":
                            catch_end = bcp
                            break
                        bcp = bcp - 1
                    日志("comp_try: 捕获体结束=" + 转字符串(catch_end) + " (有下一个捕获)")
                elif finally_pos != 0:
                    catch_end = finally_pos
                    bcp = catch_end - 1
                    while bcp >= 0:
                        bt = 列表获取(toks, bcp)
                        if 列表获取(bt, 0) == "DEDENT":
                            catch_end = bcp
                            break
                        bcp = bcp - 1
                    日志("comp_try: 捕获体结束=" + 转字符串(catch_end) + " (有最终)")
                else:
                    日志("comp_try: 捕获体结束=" + 转字符串(catch_end) + " (try_end)")
                # 解析捕获类型和变量
                catch_type = ""
                catch_var = ""
                catch_body_start = cp + 1
                ctp = cp + 1
                # 跳过 NEWLINE 和 INDENT
                if ctp < 列表长度(toks):
                    ct = 列表获取(toks, ctp)
                    if 列表获取(ct, 0) == "NEWLINE":
                        ctp = ctp + 1
                if ctp < 列表长度(toks):
                    ct = 列表获取(toks, ctp)
                    if 列表获取(ct, 0) == "INDENT":
                        catch_body_start = ctp + 1
                        ctp = ctp + 1
                找类型 = 真
                while ctp < catch_end and 找类型:
                    ct = 列表获取(toks, ctp)
                    ctt = 列表获取(ct, 0)
                    if ctt == "LPAREN":
                        if catch_type == "":
                            catch_body_start = ctp
                        else:
                            catch_body_start = ctp + 1
                        找类型 = 假
                    if 找类型 and (ctt == "ID" or ctt == "KW"):
                        if catch_type == "":
                            if ctt == "ID" and (ctp + 1) < catch_end:
                                ntok = 列表获取(toks, ctp + 1)
                                if 列表获取(ntok, 0) == "LPAREN":
                                    catch_body_start = ctp
                                    找类型 = 假
                                else:
                                    catch_type = 列表获取(ct, 1)
                                    ctp = ctp + 1
                            else:
                                catch_type = 列表获取(ct, 1)
                                ctp = ctp + 1
                    if 找类型 and catch_type != "" and ctt == "ID":
                        ctv = 列表获取(ct, 1)
                        if ctv == "as":
                            ctp = ctp + 1
                            if ctp < catch_end:
                                vt = 列表获取(toks, ctp)
                                catch_var = 列表获取(vt, 1)
                                ctp = ctp + 1
                            catch_body_start = ctp
                            找类型 = 假
                        else:
                            catch_body_start = ctp
                            找类型 = 假
                    if 找类型 and catch_type != "" and ctt != "ID":
                        catch_body_start = ctp
                        找类型 = 假
                    if 找类型 and ctt != "LPAREN" and ctt != "ID" and ctt != "KW":
                        catch_body_start = ctp
                        找类型 = 假
                except_line = indent + "except"
                if catch_type != "":
                    mapped_type = 异常类型映射(catch_type)
                    except_line = except_line + " " + mapped_type
                if catch_var != "":
                    except_line = except_line + " as " + catch_var
                except_line = except_line + ":\n"
                out = out + except_line
                catch_result = compile_block(toks, catch_body_start, catch_end, body_indent, "")
                out = out + catch_result
                ci = ci + 1
            if finally_pos != 0:
                finally_body_start = finally_pos + 1
                日志("comp_try: 处理最终块, finally_pos=" + 转字符串(finally_pos) + " body_start=" + 转字符串(finally_body_start))
                # 跳过 NEWLINE
                if finally_body_start < 列表长度(toks):
                    nt = 列表获取(toks, finally_body_start)
                    if 列表获取(nt, 0) == "NEWLINE":
                        finally_body_start = finally_body_start + 1
                # 跳过 INDENT
                if finally_body_start < 列表长度(toks):
                    nt = 列表获取(toks, finally_body_start)
                    if 列表获取(nt, 0) == "INDENT":
                        finally_body_start = finally_body_start + 1
                日志("comp_try: 最终块内容开始=" + 转字符串(finally_body_start) + " 结束=" + 转字符串(try_end))
                out = out + indent + "finally:\n"
                fin_result = compile_block(toks, finally_body_start, try_end, body_indent, "")
                out = out + fin_result
            return 列表创建(out, try_end + 1)
    return 列表创建("", p)

def find_matching_end(toks, p):
    """基于INDENT/DEDENT查找块边界，返回匹配DEDENT之后的位置"""
    depth = 1
    while p < 列表长度(toks):
        tt = 列表获取(列表获取(toks, p), 0)
        if tt == "INDENT":
            depth = depth + 1
        if tt == "DEDENT":
            depth = depth - 1
            if depth == 0:
                return p + 1
        p = p + 1
    return p

def compile_block(toks, p, end_p, indent, out):
    while p < end_p:
        if p < 列表长度(toks):
            tok = 列表获取(toks, p)
            tv = 列表获取(tok, 1)
            已处理 = 假
            if 已处理 == 假 and tv == "导入":
                np = p + 1
                找导入结束 = 真
                while np < 列表长度(toks) and 找导入结束:
                    nt = 列表获取(toks, np)
                    ntv = 列表获取(nt, 1)
                    if ntv == "。" or ntv == "\n":
                        找导入结束 = 假
                    else:
                        np = np + 1
                p = np
                已处理 = 真
            if 已处理 == 假 and tv == "导出":
                np = p + 1
                找导出结束 = 真
                while np < 列表长度(toks) and 找导出结束:
                    nt = 列表获取(toks, np)
                    ntv = 列表获取(nt, 1)
                    if ntv == "。":
                        np = np + 1
                        找导出结束 = 假
                    else:
                        np = np + 1
                p = np
                已处理 = 真
            if 已处理 == 假 and tv == "开启类型检查":
                out = out + indent + "类型检查开启 = 真\n"
                p = p + 1
                已处理 = 真
            if 已处理 == 假 and tv == "关闭类型检查":
                out = out + indent + "类型检查开启 = 假\n"
                p = p + 1
                已处理 = 真
            if tv == "设":
                结果 = comp_set(toks, p)
                stmt = 列表获取(结果, 0)
                np = 列表获取(结果, 1)
                out = out + add_indent(stmt, indent) + "\n"
                p = np
                已处理 = 真
            if 已处理 == 假 and tv == "如果":
                结果 = comp_if(toks, p)
                stmt = 列表获取(结果, 0)
                np = 列表获取(结果, 1)
                out = out + add_indent(stmt, indent)
                p = np
                已处理 = 真
            if 已处理 == 假 and tv == "当":
                结果 = comp_while(toks, p)
                stmt = 列表获取(结果, 0)
                np = 列表获取(结果, 1)
                out = out + add_indent(stmt, indent)
                p = np
                已处理 = 真
            if 已处理 == 假 and tv == "遍历":
                结果 = comp_for(toks, p)
                stmt = 列表获取(结果, 0)
                np = 列表获取(结果, 1)
                out = out + add_indent(stmt, indent)
                p = np
                已处理 = 真
            if 已处理 == 假 and tv == "返回":
                结果 = find_ret(toks, p)
                stmt = 列表获取(结果, 0)
                np = 列表获取(结果, 1)
                out = out + indent + stmt + "\n"
                p = np
                已处理 = 真
            if 已处理 == 假 and tv == "抛出":
                结果 = comp_throw(toks, p)
                stmt = 列表获取(结果, 0)
                np = 列表获取(结果, 1)
                out = out + indent + stmt + "\n"
                p = np
                已处理 = 真
            if 已处理 == 假 and tv == "尝试":
                结果 = comp_try(toks, p, indent)
                stmt = 列表获取(结果, 0)
                np = 列表获取(结果, 1)
                out = out + stmt
                p = np
                已处理 = 真
            if 已处理 == 假 and tv == "类":
                结果 = compile_class(toks, p)
                class_code = 列表获取(结果, 0)
                np = 列表获取(结果, 1)
                out = out + add_indent(class_code, indent) + "\n"
                p = np
                已处理 = 真
            if 已处理 == 假 and 列表获取(tok, 0) == "ID":
                np = p + 1
                if np < 列表长度(toks):
                    ntok = 列表获取(toks, np)
                    if 列表获取(ntok, 0) == "LPAREN":
                        结果 = 表达式(toks, p)
                        stmt = 列表获取(结果, 0)
                        np = 列表获取(结果, 1)
                        out = out + indent + stmt + "\n"
                        p = np
                        已处理 = 真
                    if 已处理 == 假 and 列表获取(ntok, 0) == "DOT":
                        结果 = 表达式(toks, p)
                        stmt = 列表获取(结果, 0)
                        np = 列表获取(结果, 1)
                        out = out + indent + stmt + "\n"
                        p = np
                        已处理 = 真
            if 已处理 == 假 and 列表获取(tok, 0) == "KW" and tv == "父":
                np = p + 1
                if np < 列表长度(toks):
                    ntok = 列表获取(toks, np)
                    if 列表获取(ntok, 0) == "DOT":
                        结果 = 表达式(toks, p)
                        stmt = 列表获取(结果, 0)
                        np = 列表获取(结果, 1)
                        out = out + indent + stmt + "\n"
                        p = np
                        已处理 = 真
            if 已处理 == 假 and 列表获取(tok, 0) == "KW" and tv == "己":
                np = p + 1
                if np < 列表长度(toks):
                    ntok = 列表获取(toks, np)
                    if 列表获取(ntok, 0) == "DOT":
                        结果 = 表达式(toks, p)
                        stmt = 列表获取(结果, 0)
                        np = 列表获取(结果, 1)
                        out = out + indent + stmt + "\n"
                        p = np
                        已处理 = 真
            if 已处理 == 假 and 列表获取(tok, 0) == "DOT":
                已处理 = 真
                p = p + 1
            if 已处理 == 假:
                p = p + 1
    return out

def add_indent(text, indent):
    有尾换行 = 假
    if 字符串长度(text) > 0:
        末字符 = 字符串获取(text, 字符串长度(text) - 1)
        if 末字符 == "\n":
            有尾换行 = 真
    if 有尾换行:
        text = 截取(text, 0, 字符串长度(text) - 1)
    结果 = indent + 加缩进行(text, indent, "", 0)
    if 有尾换行:
        return 结果 + "\n"
    return 结果

def 加缩进行(text, indent, acc, i):
    while i < 字符串长度(text):
        c = 字符串获取(text, i)
        if c == "\n":
            acc = acc + "\n" + indent
        else:
            acc = acc + c
        i = i + 1
    return acc

def comp_if(toks, p):
    if p < 列表长度(toks):
        tok = 列表获取(toks, p)
        if 列表获取(tok, 1) == "如果":
            np = p + 1
            结果 = 表达式(toks, np)
            cond = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            # 跳过 NEWLINE
            if np < 列表长度(toks):
                nt = 列表获取(toks, np)
                if 列表获取(nt, 0) == "NEWLINE":
                    np = np + 1
            # 跳过 INDENT
            if np < 列表长度(toks):
                nt = 列表获取(toks, np)
                if 列表获取(nt, 0) == "INDENT":
                    np = np + 1
            end_p = find_matching_end(toks, np)
            body = compile_block(toks, np, end_p - 1, "    ", "")
            if body == "":
                body = "    pass\n"
            code = "if " + cond + ":\n" + body
            if end_p < 列表长度(toks):
                next_tok = 列表获取(toks, end_p)
                if 列表获取(next_tok, 0) == "KW" and 列表获取(next_tok, 1) == "否则":
                    else_p = end_p + 1
                    # 跳过 NEWLINE
                    if else_p < 列表长度(toks):
                        nt = 列表获取(toks, else_p)
                        if 列表获取(nt, 0) == "NEWLINE":
                            else_p = else_p + 1
                    # 跳过 INDENT
                    if else_p < 列表长度(toks):
                        nt = 列表获取(toks, else_p)
                        if 列表获取(nt, 0) == "INDENT":
                            else_p = else_p + 1
                    else_end = find_matching_end(toks, else_p)
                    else_body = compile_block(toks, else_p, else_end - 1, "    ", "")
                    if else_body == "":
                        else_body = "    pass"
                    code = code + "\nelse:\n" + else_body
                    return 列表创建(code, else_end)
            return 列表创建(code, end_p)
    return 列表创建("", p)

def comp_while(toks, p):
    if p < 列表长度(toks):
        tok = 列表获取(toks, p)
        if 列表获取(tok, 1) == "当":
            np = p + 1
            结果 = 表达式(toks, np)
            cond = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            # 跳过 NEWLINE
            if np < 列表长度(toks):
                nt = 列表获取(toks, np)
                if 列表获取(nt, 0) == "NEWLINE":
                    np = np + 1
            # 跳过 INDENT
            if np < 列表长度(toks):
                nt = 列表获取(toks, np)
                if 列表获取(nt, 0) == "INDENT":
                    np = np + 1
            end_p = find_matching_end(toks, np)
            body = compile_block(toks, np, end_p - 1, "    ", "")
            if body == "":
                body = "    pass\n"
            return 列表创建("while " + cond + ":\n" + body, end_p)
    return 列表创建("", p)

def comp_for(toks, p):
    if p < 列表长度(toks):
        tok = 列表获取(toks, p)
        if 列表获取(tok, 1) == "遍历":
            np = p + 1
            if np < 列表长度(toks):
                var_tok = 列表获取(toks, np)
                var_name = 列表获取(var_tok, 1)
                np = np + 1
                if np < 列表长度(toks):
                    next_tok = 列表获取(toks, np)
                    if 列表获取(next_tok, 1) == "在":
                        np = np + 1
                        结果 = 表达式(toks, np)
                        iter_expr = 列表获取(结果, 0)
                        np = 列表获取(结果, 1)
                        # 跳过 NEWLINE
                        if np < 列表长度(toks):
                            nt = 列表获取(toks, np)
                            if 列表获取(nt, 0) == "NEWLINE":
                                np = np + 1
                        # 跳过 INDENT
                        if np < 列表长度(toks):
                            nt = 列表获取(toks, np)
                            if 列表获取(nt, 0) == "INDENT":
                                np = np + 1
                        end_p = find_matching_end(toks, np)
                        body = compile_block(toks, np, end_p - 1, "    ", "")
                        if body == "":
                            body = "    pass\n"
                        return 列表创建("for " + var_name + " in " + iter_expr + ":\n" + body, end_p)
    return 列表创建("", p)

def compile_stmts(toks, p, out):
    while p < 列表长度(toks):
        tok = 列表获取(toks, p)
        tv = 列表获取(tok, 1)
        已处理 = 假
        if 已处理 == 假 and tv == "开启类型检查":
            out = out + "    类型检查开启 = 真\n"
            p = p + 1
            已处理 = 真
        if 已处理 == 假 and tv == "关闭类型检查":
            out = out + "    类型检查开启 = 假\n"
            p = p + 1
            已处理 = 真
        if tv == "设":
            结果 = comp_set(toks, p)
            stmt = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            out = out + add_indent(stmt, "    ") + "\n"
            p = np
            已处理 = 真
        if 已处理 == 假 and tv == "如果":
            结果 = comp_if(toks, p)
            stmt = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            out = out + add_indent(stmt, "    ")
            p = np
            已处理 = 真
        if 已处理 == 假 and tv == "当":
            结果 = comp_while(toks, p)
            stmt = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            out = out + add_indent(stmt, "    ")
            p = np
            已处理 = 真
        if 已处理 == 假 and tv == "遍历":
            结果 = comp_for(toks, p)
            stmt = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            out = out + add_indent(stmt, "    ")
            p = np
            已处理 = 真
        if 已处理 == 假 and tv == "返回":
            结果 = find_ret(toks, p)
            stmt = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            out = out + "    " + stmt + "\n"
            p = np
            已处理 = 真
        if 已处理 == 假 and tv == "抛出":
            结果 = comp_throw(toks, p)
            stmt = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            out = out + "    " + stmt + "\n"
            p = np
            已处理 = 真
        if 已处理 == 假 and tv == "尝试":
            结果 = comp_try(toks, p, "    ")
            stmt = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            out = out + stmt
            p = np
            已处理 = 真
        if 已处理 == 假 and tv == "类":
            结果 = compile_class(toks, p)
            class_code = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            out = out + add_indent(class_code, "    ") + "\n"
            p = np
            已处理 = 真
        if 已处理 == 假 and 列表获取(tok, 0) == "ID":
            np = p + 1
            if np < 列表长度(toks):
                ntok = 列表获取(toks, np)
                if 列表获取(ntok, 0) == "LPAREN":
                    结果 = 表达式(toks, p)
                    stmt = 列表获取(结果, 0)
                    np = 列表获取(结果, 1)
                    out = out + "    " + stmt + "\n"
                    p = np
                    已处理 = 真
                if 已处理 == 假 and 列表获取(ntok, 0) == "DOT":
                    结果 = 表达式(toks, p)
                    stmt = 列表获取(结果, 0)
                    np = 列表获取(结果, 1)
                    out = out + "    " + stmt + "\n"
                    p = np
                    已处理 = 真
        if 已处理 == 假 and 列表获取(tok, 0) == "KW" and tv == "父":
            np = p + 1
            if np < 列表长度(toks):
                ntok = 列表获取(toks, np)
                if 列表获取(ntok, 0) == "DOT":
                    结果 = 表达式(toks, p)
                    stmt = 列表获取(结果, 0)
                    np = 列表获取(结果, 1)
                    out = out + "    " + stmt + "\n"
                    p = np
                    已处理 = 真
        if 已处理 == 假 and 列表获取(tok, 0) == "KW" and tv == "己":
            np = p + 1
            if np < 列表长度(toks):
                ntok = 列表获取(toks, np)
                if 列表获取(ntok, 0) == "DOT":
                    结果 = 表达式(toks, p)
                    stmt = 列表获取(结果, 0)
                    np = 列表获取(结果, 1)
                    out = out + "    " + stmt + "\n"
                    p = np
                    已处理 = 真
        if 已处理 == 假 and 是函数关键字(tv):
            return 列表创建(out, p)
        if 已处理 == 假:
            p = p + 1
    return 列表创建(out, p)

def 解析参数(toks, p):
    if p < 列表长度(toks):
        tok = 列表获取(toks, p)
        if 列表获取(tok, 1) == "接收":
            return 收集参数(toks, p + 1, "")
    return 列表创建("", p)

def 收集参数(toks, p, acc):
    while p < 列表长度(toks):
        tok = 列表获取(toks, p)
        已处理 = 假
        if 列表获取(tok, 0) == "ID":
            v = 列表获取(tok, 1)
            if 字符串长度(v) > 0:
                末字符 = 字符串获取(v, 字符串长度(v) - 1)
                if 末字符 == "：":
                    v = 截取(v, 0, 字符串长度(v) - 1)
                    if acc == "":
                        return 列表创建(v, p + 1)
                    return 列表创建(acc + ", " + v, p + 1)
            param_entry = v
            p = p + 1
            # 检查是否有类型注解（参数名后紧跟类型名，支持复合类型）
            if p < 列表长度(toks):
                type_result = 解析类型(toks, p)
                resolved_type = 列表获取(type_result, 0)
                if resolved_type != "":
                    param_entry = v + ": " + resolved_type
                    p = 列表获取(type_result, 1)
            if acc == "":
                acc = param_entry
            else:
                acc = acc + ", " + param_entry
            已处理 = 真
        if 已处理 == 假 and 列表获取(tok, 0) == "KW":
            v = 列表获取(tok, 1)
            if v == "己":
                if acc == "":
                    acc = v
                else:
                    acc = acc + ", " + v
                p = p + 1
                已处理 = 真
        if 已处理 == 假 and 列表获取(tok, 0) == "COMMA":
            p = p + 1
            已处理 = 真
        if 已处理 == 假:
            return 列表创建(acc, p)
    return 列表创建(acc, p)

def compile_class(toks, p):
    if p < 列表长度(toks):
        tok = 列表获取(toks, p)
        if 列表获取(tok, 1) == "类":
            np = p + 1
            name = ""
            if np < 列表长度(toks):
                name_tok = 列表获取(toks, np)
                name = 列表获取(name_tok, 1)
                np = np + 1
            parent_name = ""
            if np < 列表长度(toks):
                next_tok = 列表获取(toks, np)
                if 列表获取(next_tok, 0) == "LPAREN":
                    np = np + 1
                    if np < 列表长度(toks):
                        parent_tok = 列表获取(toks, np)
                        parent_name = 列表获取(parent_tok, 1)
                        np = np + 1
                        if np < 列表长度(toks):
                            rparen_tok = 列表获取(toks, np)
                            if 列表获取(rparen_tok, 0) == "RPAREN":
                                np = np + 1
            # 跳过 NEWLINE
            if np < 列表长度(toks):
                nt = 列表获取(toks, np)
                if 列表获取(nt, 0) == "NEWLINE":
                    np = np + 1
            # 跳过 INDENT
            if np < 列表长度(toks):
                nt = 列表获取(toks, np)
                if 列表获取(nt, 0) == "INDENT":
                    np = np + 1
            end_p = find_matching_end(toks, np)
            body = compile_class_body(toks, np, end_p - 1, name)
            if body == "":
                body = "    pass"
            class_def = "class " + name
            if parent_name != "":
                class_def = class_def + "(" + parent_name + ")"
            class_def = class_def + ":\n" + body
            return 列表创建(class_def, end_p)
    return 列表创建("", p)

def compile_class_body(toks, p, end_p, class_name):
    out = ""
    while p < end_p and p < 列表长度(toks):
        tok = 列表获取(toks, p)
        tv = 列表获取(tok, 1)
        已处理 = 假
        if tv == "属性":
            np = p + 1
            if np < 列表长度(toks):
                p = np + 1
                已处理 = 真
        if 已处理 == 假 and 是函数关键字(tv):
            func结果 = compile_class_method(toks, p, class_name)
            method_code = 列表获取(func结果, 0)
            p = 列表获取(func结果, 1)
            out = out + method_code
            已处理 = 真
        if 已处理 == 假:
            p = p + 1
    return out

def compile_class_method(toks, p, class_name):
    tok = 列表获取(toks, p)
    np = p + 1
    name = ""
    if np < 列表长度(toks):
        name_tok = 列表获取(toks, np)
        name = 列表获取(name_tok, 1)
        np = np + 1
    参数结果 = 解析参数(toks, np)
    params = 列表获取(参数结果, 0)
    np = 列表获取(参数结果, 1)
    final_params = ""
    if params == "己":
        final_params = "self"
    if params != "己" and 字符串长度(params) >= 2:
        前两字 = 截取(params, 0, 2)
        if 前两字 == "己,":
            final_params = "self" + 截取(params, 1, 字符串长度(params))
    if final_params == "":
        final_params = "self"
        if params != "":
            final_params = "self, " + params
    # 检查返回类型
    return_type = ""
    if np < 列表长度(toks):
        tok = 列表获取(toks, np)
        if 列表获取(tok, 0) == "KW" and 列表获取(tok, 1) == "返回":
            np = np + 1
            if np < 列表长度(toks):
                type_result = 解析类型(toks, np)
                resolved_type = 列表获取(type_result, 0)
                if resolved_type != "":
                    return_type = " -> " + resolved_type
                    np = 列表获取(type_result, 1)
    # 跳过 NEWLINE
    if np < 列表长度(toks):
        nt = 列表获取(toks, np)
        if 列表获取(nt, 0) == "NEWLINE":
            np = np + 1
    # 跳过 INDENT
    if np < 列表长度(toks):
        nt = 列表获取(toks, np)
        if 列表获取(nt, 0) == "INDENT":
            np = np + 1
    method_end = find_matching_end(toks, np)
    body = compile_block(toks, np, method_end - 1, "        ", "")
    if body == "":
        body = "        pass"
    code = "    def " + name + "(" + final_params + ")" + return_type + ":\n" + body + "\n"
    return 列表创建(code, method_end)

def compile_top(toks, p, out):
    while p < 列表长度(toks):
        tok = 列表获取(toks, p)
        tv = 列表获取(tok, 1)
        已处理 = 假
        if tv == "类":
            结果 = compile_class(toks, p)
            class_code = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            out = out + class_code + "\n"
            p = np
            已处理 = 真
        if 已处理 == 假 and 是函数关键字(tv):
            结果 = compile_single_func(toks, p)
            func_code = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            out = out + func_code
            p = np
            已处理 = 真
        if 已处理 == 假 and tv == "抛出":
            结果 = comp_throw(toks, p)
            stmt = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            out = out + stmt + "\n"
            p = np
            已处理 = 真
        if 已处理 == 假 and tv == "尝试":
            结果 = comp_try(toks, p, "")
            stmt = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            out = out + stmt
            p = np
            已处理 = 真
        if 已处理 == 假:
            p = p + 1
    return out

def compile_single_func(toks, p):
    tok = 列表获取(toks, p)
    np = p + 1
    name = ""
    if np < 列表长度(toks):
        tok = 列表获取(toks, np)
        if 列表获取(tok, 0) == "ID":
            name = 列表获取(tok, 1)
            np = np + 1
    if np < 列表长度(toks):
        tok = 列表获取(toks, np)
        if 列表获取(tok, 0) == "KW" and 列表获取(tok, 1) == "导出":
            np = np + 1
    参数结果 = 解析参数(toks, np)
    params = 列表获取(参数结果, 0)
    np = 列表获取(参数结果, 1)
    # 检查返回类型
    return_type = ""
    if np < 列表长度(toks):
        tok = 列表获取(toks, np)
        if 列表获取(tok, 0) == "KW" and 列表获取(tok, 1) == "返回":
            np = np + 1
            if np < 列表长度(toks):
                type_result = 解析类型(toks, np)
                resolved_type = 列表获取(type_result, 0)
                if resolved_type != "":
                    return_type = " -> " + resolved_type
                    np = 列表获取(type_result, 1)
    # 跳过 NEWLINE
    if np < 列表长度(toks):
        nt = 列表获取(toks, np)
        if 列表获取(nt, 0) == "NEWLINE":
            np = np + 1
    # 跳过 INDENT
    if np < 列表长度(toks):
        nt = 列表获取(toks, np)
        if 列表获取(nt, 0) == "INDENT":
            np = np + 1
    body_end = find_matching_end(toks, np)
    body = compile_block(toks, np, body_end - 1, "    ", "")
    if body == "":
        body = "    pass\n"
    code = "def " + name + "(" + params + ")" + return_type + ":\n" + body + "\n"
    return 列表创建(code, body_end)

def 压缩代码(src):
    n = 字符串长度(src)
    out = ""
    p = 0
    行缓冲 = ""
    换行计数 = 0
    while p < n:
        c = 字符串获取(src, p)
        if c == "\n":
            修剪后 = ""
            i = 字符串长度(行缓冲) - 1
            继续循环 = 真
            while 继续循环 and i >= 0:
                ch = 字符串获取(行缓冲, i)
                if ch != " " and ch != "\t":
                    修剪后 = 截取(行缓冲, 0, i + 1)
                    继续循环 = 假
                else:
                    i = i - 1
            if 修剪后 == "":
                换行计数 = 换行计数 + 1
                if 换行计数 <= 1:
                    out = out + "\n"
                else:
                    换行计数 = 0
                    out = out + 修剪后 + "\n"
            else:
                换行计数 = 0
                out = out + 修剪后 + "\n"
            行缓冲 = ""
        else:
            行缓冲 = 行缓冲 + c
        p = p + 1
    if 行缓冲 != "":
        out = out + 行缓冲
    return out

def 编译(src):
    header = "# Generated by Duan Level 6\n类型检查开启 = 假\n"
    toks = 词法(src)
    code = compile_top(toks, 0, "")
    result = header + code
    return 压缩代码(result)

def 测试():
    # 测试无空格分词
    print("测试无空格分词:")
    测试tok = 词法("段foo接收a返回a加 1结束")
    print(测试tok)
    
    # 测试基本编译
    src1 = "段落 foo 返回 42 结束"
    print(编译(src1))
    
    src2 = "段落 bar 设 x 为 10 返回 x 结束"
    print(编译(src2))

def 主函数():
    测试()