# Generated by Duan Level 3
def 是关键字(w):
    if w == "设":
        return 真
    if w == "段落":
        return 真
    if w == "段":
        return 真
    if w == "返回":
        return 真
    if w == "结束":
        return 真
    if w == "为":
        return 真
    if w == "如果":
        return 真
    if w == "否则":
        return 真
    if w == "当":
        return 真
    if w == "接收":
        return 真
    if w == "加":
        return 真
    if w == "减":
        return 真
    if w == "乘":
        return 真
    if w == "除":
        return 真
    if w == "取模":
        return 真
    if w == "等于":
        return 真
    if w == "小于":
        return 真
    if w == "大于":
        return 真
    if w == "小于等于":
        return 真
    if w == "大于等于":
        return 真
    if w == "不等于":
        return 真
    if w == "且":
        return 真
    if w == "或":
        return 真
    if w == "非":
        return 真
    if w == "遍历":
        return 真
    if w == "在":
        return 真
    if w == "类":
        return 真
    if w == "属性":
        return 真
    if w == "己":
        return 真
    return 假

def 是函数关键字(w):
    if w == "段落":
        return 真
    if w == "段":
        return 真
    return 假

def 建(t, v):
    return 列表创建(t, v)

def 词(src, p, n, s):
    if p < n:
        c = 字符串获取(src, p)
        if c == "：":
            if s == "":
                return 建("EOF", "")
            if 是关键字(s):
                return 建("KW", s)
            return 建("ID", s)
        if c == "。":
            if s == "":
                return 建("EOF", "")
            if 是关键字(s):
                return 建("KW", s)
            return 建("ID", s)
        if c == "，":
            if s == "":
                return 建("EOF", "")
            if 是关键字(s):
                return 建("KW", s)
            return 建("ID", s)
        if c >= "a":
            return 词(src, p + 1, n, s + c)
        if c >= "A":
            return 词(src, p + 1, n, s + c)
        if c >= "一":
            return 词(src, p + 1, n, s + c)
        if c >= "0":
            if c <= "9":
                if s != "":
                    return 词(src, p + 1, n, s + c)
    if s == "":
        return 建("EOF", "")
    if 是关键字(s):
        return 建("KW", s)
    return 建("ID", s)

def 数字(src, p, n, s):
    if p < n:
        c = 字符串获取(src, p)
        if c >= "0":
            if c <= "9":
                return 数字(src, p + 1, n, s + c)
    return 建("NUM", s)

def 字符串(src, p, n, s):
    if p < n:
        c = 字符串获取(src, p)
        if c == "\"":
            tok = 建("STR", s)
            return 列表创建(tok, p + 1)
        return 字符串(src, p + 1, n, s + c)
    tok = 建("STR", s)
    return 列表创建(tok, p)

def 扫注释(src, p, n):
    if p < n:
        c = 字符串获取(src, p)
        if c == "\n":
            return p + 1
        return 扫注释(src, p + 1, n)
    return p

def 扫(src, p, n, toks):
    while p < n:
        c = 字符串获取(src, p)
        已处理 = 假
        if c == " ":
            p = p + 1
            已处理 = 真
        if 已处理 == 假 and c == "\n":
            p = p + 1
            已处理 = 真
        if 已处理 == 假 and c == "#":
            p = 扫注释(src, p + 1, n)
            已处理 = 真
        if 已处理 == 假 and c == "'":
            if p + 1 < n:
                nc = 字符串获取(src, p + 1)
                if nc == "\"":
                    列表追加(toks, 建("STR", "\""))
                    p = p + 3
                    已处理 = 真
            if 已处理 == 假:
                p = p + 1
                已处理 = 真
        if 已处理 == 假 and c == "\"":
            if p + 1 < n:
                nc = 字符串获取(src, p + 1)
                if nc == "'":
                    列表追加(toks, 建("STR", "'"))
                    p = p + 3
                    已处理 = 真
            if 已处理 == 假:
                结果 = 字符串(src, p + 1, n, "")
                tok = 列表获取(结果, 0)
                p = 列表获取(结果, 1)
                列表追加(toks, tok)
                已处理 = 真
        if 已处理 == 假 and c == "：":
            p = p + 1
            已处理 = 真
        if 已处理 == 假 and c == "。":
            p = p + 1
            已处理 = 真
        if 已处理 == 假 and c == "，":
            p = p + 1
            已处理 = 真
        if 已处理 == 假 and c == "(":
            列表追加(toks, 建("LPAREN", "("))
            p = p + 1
            已处理 = 真
        if 已处理 == 假 and c == ")":
            列表追加(toks, 建("RPAREN", ")"))
            p = p + 1
            已处理 = 真
        if 已处理 == 假 and c == ",":
            列表追加(toks, 建("COMMA", ","))
            p = p + 1
            已处理 = 真
        if 已处理 == 假 and c >= "0":
            if c <= "9":
                tok = 数字(src, p, n, "")
                列表追加(toks, tok)
                p = p + 字符串长度(列表获取(tok, 1))
                已处理 = 真
        if 已处理 == 假 and c >= "a":
            tok = 词(src, p, n, "")
            列表追加(toks, tok)
            p = p + 字符串长度(列表获取(tok, 1))
            已处理 = 真
        if 已处理 == 假 and c >= "A":
            tok = 词(src, p, n, "")
            列表追加(toks, tok)
            p = p + 字符串长度(列表获取(tok, 1))
            已处理 = 真
        if 已处理 == 假 and c >= "一":
            tok = 词(src, p, n, "")
            列表追加(toks, tok)
            p = p + 字符串长度(列表获取(tok, 1))
            已处理 = 真
        if 已处理 == 假:
            p = p + 1
    return toks

def 词法(src):
    return 扫(src, 0, 字符串长度(src), 列表创建())

def 表达式(toks, p):
    return 或表达式(toks, p)

def 或表达式(toks, p):
    结果 = 且表达式(toks, p)
    left = 列表获取(结果, 0)
    np = 列表获取(结果, 1)
    继续循环 = 真
    while 继续循环 and np < 列表长度(toks):
        tok = 列表获取(toks, np)
        tv = 列表获取(tok, 1)
        if tv != "或":
            继续循环 = 假
        
        else:
            右结果 = 且表达式(toks, np + 1)
            right = 列表获取(右结果, 0)
            np = 列表获取(右结果, 1)
            left = left + " or " + right
    return 列表创建(left, np)

def 且表达式(toks, p):
    结果 = 比较表达式(toks, p)
    left = 列表获取(结果, 0)
    np = 列表获取(结果, 1)
    继续循环 = 真
    while 继续循环 and np < 列表长度(toks):
        tok = 列表获取(toks, np)
        tv = 列表获取(tok, 1)
        if tv != "且":
            继续循环 = 假
        
        else:
            右结果 = 比较表达式(toks, np + 1)
            right = 列表获取(右结果, 0)
            np = 列表获取(右结果, 1)
            left = left + " and " + right
    return 列表创建(left, np)

def 比较表达式(toks, p):
    结果 = 加减表达式(toks, p)
    left = 列表获取(结果, 0)
    np = 列表获取(结果, 1)
    if np < 列表长度(toks):
        tok = 列表获取(toks, np)
        tv = 列表获取(tok, 1)
        if tv == "等于":
            右结果 = 加减表达式(toks, np + 1)
            right = 列表获取(右结果, 0)
            np = 列表获取(右结果, 1)
            return 列表创建(left + " == " + right, np)
        if tv == "小于":
            右结果 = 加减表达式(toks, np + 1)
            right = 列表获取(右结果, 0)
            np = 列表获取(右结果, 1)
            return 列表创建(left + " < " + right, np)
        if tv == "大于":
            右结果 = 加减表达式(toks, np + 1)
            right = 列表获取(右结果, 0)
            np = 列表获取(右结果, 1)
            return 列表创建(left + " > " + right, np)
        if tv == "小于等于":
            右结果 = 加减表达式(toks, np + 1)
            right = 列表获取(右结果, 0)
            np = 列表获取(右结果, 1)
            return 列表创建(left + " <= " + right, np)
        if tv == "大于等于":
            右结果 = 加减表达式(toks, np + 1)
            right = 列表获取(右结果, 0)
            np = 列表获取(右结果, 1)
            return 列表创建(left + " >= " + right, np)
        if tv == "不等于":
            右结果 = 加减表达式(toks, np + 1)
            right = 列表获取(右结果, 0)
            np = 列表获取(右结果, 1)
            return 列表创建(left + " != " + right, np)
    return 列表创建(left, np)

def 加减表达式(toks, p):
    结果 = 乘除表达式(toks, p)
    left = 列表获取(结果, 0)
    np = 列表获取(结果, 1)
    继续循环 = 真
    while 继续循环 and np < 列表长度(toks):
        tok = 列表获取(toks, np)
        tv = 列表获取(tok, 1)
        if tv == "加":
            右结果 = 乘除表达式(toks, np + 1)
            right = 列表获取(右结果, 0)
            np = 列表获取(右结果, 1)
            left = left + " + " + right
        
        else:
            if tv == "减":
                右结果 = 乘除表达式(toks, np + 1)
                right = 列表获取(右结果, 0)
                np = 列表获取(右结果, 1)
                left = left + " - " + right
            
            else:
                继续循环 = 假
    return 列表创建(left, np)

def 乘除表达式(toks, p):
    结果 = 一元表达式(toks, p)
    left = 列表获取(结果, 0)
    np = 列表获取(结果, 1)
    继续循环 = 真
    while 继续循环 and np < 列表长度(toks):
        tok = 列表获取(toks, np)
        tv = 列表获取(tok, 1)
        if tv == "乘":
            右结果 = 一元表达式(toks, np + 1)
            right = 列表获取(右结果, 0)
            np = 列表获取(右结果, 1)
            left = left + " * " + right
        
        else:
            if tv == "除":
                右结果 = 一元表达式(toks, np + 1)
                right = 列表获取(右结果, 0)
                np = 列表获取(右结果, 1)
                left = left + " // " + right
            
            else:
                if tv == "取模":
                    右结果 = 一元表达式(toks, np + 1)
                    right = 列表获取(右结果, 0)
                    np = 列表获取(右结果, 1)
                    left = left + " % " + right
                
                else:
                    继续循环 = 假
    return 列表创建(left, np)

def 一元表达式(toks, p):
    if p < 列表长度(toks):
        tok = 列表获取(toks, p)
        if 列表获取(tok, 0) == "KW" and 列表获取(tok, 1) == "非":
            结果 = 一元表达式(toks, p + 1)
            expr = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            return 列表创建("not " + expr, np)
        if 列表获取(tok, 0) == "LPAREN":
            结果 = 表达式(toks, p + 1)
            expr = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            if np < 列表长度(toks):
                tok = 列表获取(toks, np)
                if 列表获取(tok, 0) == "RPAREN":
                    return 列表创建(expr, np + 1)
            return 列表创建(expr, np)
        if 列表获取(tok, 0) == "NUM":
            return 列表创建(列表获取(tok, 1), p + 1)
        if 列表获取(tok, 0) == "STR":
            s = 列表获取(tok, 1)
            有单引号 = 假
            i = 0
            while i < 字符串长度(s):
                if 字符串获取(s, i) == "'":
                    有单引号 = 真
                i = i + 1
            if 有单引号:
                return 列表创建("\"" + s + "\"", p + 1)
            return 列表创建("'" + s + "'", p + 1)
        if 列表获取(tok, 0) == "ID":
            name = 列表获取(tok, 1)
            np = p + 1
            if np < 列表长度(toks):
                tok = 列表获取(toks, np)
                if 列表获取(tok, 0) == "LPAREN":
                    参数结果 = 解析参数列表(toks, np + 1)
                    args = 列表获取(参数结果, 0)
                    np = 列表获取(参数结果, 1)
                    return 列表创建(name + "(" + args + ")", np)
            return 列表创建(name, np)
    return 列表创建("None", p)

def 解析参数列表(toks, p):
    if p < 列表长度(toks):
        tok = 列表获取(toks, p)
        if 列表获取(tok, 0) == "RPAREN":
            return 列表创建("", p + 1)
        结果 = 表达式(toks, p)
        first = 列表获取(结果, 0)
        np = 列表获取(结果, 1)
        剩余结果 = 解析更多参数(toks, np, first)
        return 剩余结果
    return 列表创建("", p)

def 解析更多参数(toks, p, acc):
    while p < 列表长度(toks):
        tok = 列表获取(toks, p)
        if 列表获取(tok, 0) == "RPAREN":
            return 列表创建(acc, p + 1)
        if 列表获取(tok, 0) == "COMMA":
            结果 = 表达式(toks, p + 1)
            next_arg = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            acc = acc + ", " + next_arg
            p = np
        
        else:
            p = p + 1
    return 列表创建(acc, p)

def find_ret(toks, p):
    if p < 列表长度(toks):
        tok = 列表获取(toks, p)
        if 列表获取(tok, 1) == "返回":
            结果 = 表达式(toks, p + 1)
            expr = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            return 列表创建("return " + expr, np)
    return 列表创建("pass", p)

def find_end(toks, p):
    while p < 列表长度(toks):
        tok = 列表获取(toks, p)
        if 列表获取(tok, 0) == "KW":
            if 列表获取(tok, 1) == "结束":
                return p + 1
            if 是函数关键字(列表获取(tok, 1)):
                return p
        p = p + 1
    return p

def find_next(toks, p):
    while p < 列表长度(toks):
        tok = 列表获取(toks, p)
        if 列表获取(tok, 0) == "KW":
            tv = 列表获取(tok, 1)
            if 是函数关键字(tv):
                return p
            if tv == "结束":
                return p
            if tv == "设":
                return p
            if tv == "如果":
                return p
            if tv == "返回":
                return p
        p = p + 1
    return p

def comp_set(toks, p):
    if p < 列表长度(toks):
        tok = 列表获取(toks, p)
        if 列表获取(tok, 1) == "设":
            np = p + 1
            if np < 列表长度(toks):
                tok = 列表获取(toks, np)
                var = 列表获取(tok, 1)
                np = np + 1
                if np < 列表长度(toks):
                    tok = 列表获取(toks, np)
                    if 列表获取(tok, 1) == "为":
                        np = np + 1
                        结果 = 表达式(toks, np)
                        expr = 列表获取(结果, 0)
                        np = 列表获取(结果, 1)
                        return 列表创建(var + " = " + expr, np)
    return 列表创建("", p)

def find_matching_end(toks, p, level):
    while p < 列表长度(toks):
        tok = 列表获取(toks, p)
        if 列表获取(tok, 0) == "KW":
            tv = 列表获取(tok, 1)
            if tv == "如果":
                level = level + 1
            if tv == "当":
                level = level + 1
            if tv == "遍历":
                level = level + 1
            if tv == "类":
                level = level + 1
            if tv == "段落":
                level = level + 1
            if tv == "段":
                level = level + 1
            if tv == "否则":
                if level == 1:
                    return p
            if tv == "结束":
                if level == 1:
                    return p + 1
                level = level - 1
        p = p + 1
    return p

def compile_block(toks, p, end_p, indent, out):
    while p < end_p:
        if p < 列表长度(toks):
            tok = 列表获取(toks, p)
            tv = 列表获取(tok, 1)
            已处理 = 假
            if tv == "设":
                结果 = comp_set(toks, p)
                stmt = 列表获取(结果, 0)
                np = 列表获取(结果, 1)
                out = out + indent + stmt + "\n"
                p = np
                已处理 = 真
            if 已处理 == 假 and tv == "如果":
                结果 = comp_if(toks, p)
                stmt = 列表获取(结果, 0)
                np = 列表获取(结果, 1)
                out = out + add_indent(stmt, indent)
                p = np
                已处理 = 真
            if 已处理 == 假 and tv == "当":
                结果 = comp_while(toks, p)
                stmt = 列表获取(结果, 0)
                np = 列表获取(结果, 1)
                out = out + add_indent(stmt, indent)
                p = np
                已处理 = 真
            if 已处理 == 假 and tv == "遍历":
                结果 = comp_for(toks, p)
                stmt = 列表获取(结果, 0)
                np = 列表获取(结果, 1)
                out = out + add_indent(stmt, indent)
                p = np
                已处理 = 真
            if 已处理 == 假 and tv == "返回":
                结果 = find_ret(toks, p)
                stmt = 列表获取(结果, 0)
                np = 列表获取(结果, 1)
                out = out + indent + stmt + "\n"
                p = np
                已处理 = 真
            if 已处理 == 假 and 列表获取(tok, 0) == "ID":
                np = p + 1
                if np < 列表长度(toks):
                    ntok = 列表获取(toks, np)
                    if 列表获取(ntok, 0) == "LPAREN":
                        结果 = 表达式(toks, p)
                        stmt = 列表获取(结果, 0)
                        np = 列表获取(结果, 1)
                        out = out + indent + stmt + "\n"
                        p = np
                        已处理 = 真
            if 已处理 == 假 and tv == "结束":
                return out
            if 已处理 == 假:
                p = p + 1
    return out

def add_indent(text, indent):
    有尾换行 = 假
    if 字符串长度(text) > 0:
        末字符 = 字符串获取(text, 字符串长度(text) - 1)
        if 末字符 == "\n":
            有尾换行 = 真
    if 有尾换行:
        text = 截取(text, 0, 字符串长度(text) - 1)
    结果 = indent + 加缩进行(text, indent, "", 0)
    if 有尾换行:
        return 结果 + "\n"
    return 结果

def 加缩进行(text, indent, acc, i):
    while i < 字符串长度(text):
        c = 字符串获取(text, i)
        if c == "\n":
            acc = acc + "\n" + indent
        
        else:
            acc = acc + c
        i = i + 1
    return acc

def comp_if(toks, p):
    if p < 列表长度(toks):
        tok = 列表获取(toks, p)
        if 列表获取(tok, 1) == "如果":
            np = p + 1
            结果 = 表达式(toks, np)
            cond = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            end_p = find_matching_end(toks, np, 1)
            body = compile_block(toks, np, end_p - 1, "    ", "")
            if body == "":
                body = "    pass\n"
            code = "if " + cond + ":\n" + body
            if end_p < 列表长度(toks):
                next_tok = 列表获取(toks, end_p)
                if 列表获取(next_tok, 1) == "否则":
                    else_p = end_p + 1
                    else_end = find_matching_end(toks, else_p, 1)
                    else_body = compile_block(toks, else_p, else_end - 1, "    ", "")
                    if else_body == "":
                        else_body = "    pass"
                    code = code + "\nelse:\n" + else_body
                    return 列表创建(code, else_end)
            return 列表创建(code, end_p)
    return 列表创建("", p)

def comp_while(toks, p):
    if p < 列表长度(toks):
        tok = 列表获取(toks, p)
        if 列表获取(tok, 1) == "当":
            np = p + 1
            结果 = 表达式(toks, np)
            cond = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            end_p = find_matching_end(toks, np, 1)
            body = compile_block(toks, np, end_p - 1, "    ", "")
            if body == "":
                body = "    pass\n"
            return 列表创建("while " + cond + ":\n" + body, end_p)
    return 列表创建("", p)

def comp_for(toks, p):
    if p < 列表长度(toks):
        tok = 列表获取(toks, p)
        if 列表获取(tok, 1) == "遍历":
            np = p + 1
            if np < 列表长度(toks):
                var_tok = 列表获取(toks, np)
                var_name = 列表获取(var_tok, 1)
                np = np + 1
                if np < 列表长度(toks):
                    next_tok = 列表获取(toks, np)
                    if 列表获取(next_tok, 1) == "在":
                        np = np + 1
                        结果 = 表达式(toks, np)
                        iter_expr = 列表获取(结果, 0)
                        np = 列表获取(结果, 1)
                        end_p = find_matching_end(toks, np, 1)
                        body = compile_block(toks, np, end_p - 1, "    ", "")
                        if body == "":
                            body = "    pass\n"
                        return 列表创建("for " + var_name + " in " + iter_expr + ":\n" + body, end_p)
    return 列表创建("", p)

def compile_stmts(toks, p, out):
    while p < 列表长度(toks):
        tok = 列表获取(toks, p)
        tv = 列表获取(tok, 1)
        已处理 = 假
        if tv == "设":
            结果 = comp_set(toks, p)
            stmt = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            out = out + "    " + stmt + "\n"
            p = np
            已处理 = 真
        if 已处理 == 假 and tv == "如果":
            结果 = comp_if(toks, p)
            stmt = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            out = out + add_indent(stmt, "    ")
            p = np
            已处理 = 真
        if 已处理 == 假 and tv == "当":
            结果 = comp_while(toks, p)
            stmt = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            out = out + add_indent(stmt, "    ")
            p = np
            已处理 = 真
        if 已处理 == 假 and tv == "遍历":
            结果 = comp_for(toks, p)
            stmt = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            out = out + add_indent(stmt, "    ")
            p = np
            已处理 = 真
        if 已处理 == 假 and tv == "返回":
            结果 = find_ret(toks, p)
            stmt = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            out = out + "    " + stmt + "\n"
            p = np
            已处理 = 真
        if 已处理 == 假 and 列表获取(tok, 0) == "ID":
            np = p + 1
            if np < 列表长度(toks):
                ntok = 列表获取(toks, np)
                if 列表获取(ntok, 0) == "LPAREN":
                    结果 = 表达式(toks, p)
                    stmt = 列表获取(结果, 0)
                    np = 列表获取(结果, 1)
                    out = out + "    " + stmt + "\n"
                    p = np
                    已处理 = 真
        if 已处理 == 假 and tv == "结束":
            return 列表创建(out, p + 1)
        if 已处理 == 假 and 是函数关键字(tv):
            return 列表创建(out, p)
        if 已处理 == 假:
            p = p + 1
    return 列表创建(out, p)

def 解析参数(toks, p):
    if p < 列表长度(toks):
        tok = 列表获取(toks, p)
        if 列表获取(tok, 1) == "接收":
            return 收集参数(toks, p + 1, "")
    return 列表创建("", p)

def 收集参数(toks, p, acc):
    while p < 列表长度(toks):
        tok = 列表获取(toks, p)
        已处理 = 假
        if 列表获取(tok, 0) == "ID":
            v = 列表获取(tok, 1)
            if 字符串长度(v) > 0:
                末字符 = 字符串获取(v, 字符串长度(v) - 1)
                if 末字符 == "：":
                    v = 截取(v, 0, 字符串长度(v) - 1)
                    if acc == "":
                        return 列表创建(v, p + 1)
                    return 列表创建(acc + ", " + v, p + 1)
            if acc == "":
                acc = v
            
            else:
                acc = acc + ", " + v
            p = p + 1
            已处理 = 真
        if 已处理 == 假 and 列表获取(tok, 0) == "COMMA":
            p = p + 1
            已处理 = 真
        if 已处理 == 假:
            return 列表创建(acc, p)
    return 列表创建(acc, p)

def compile_class(toks, p):
    if p < 列表长度(toks):
        tok = 列表获取(toks, p)
        if 列表获取(tok, 1) == "类":
            np = p + 1
            name = ""
            if np < 列表长度(toks):
                name_tok = 列表获取(toks, np)
                name = 列表获取(name_tok, 1)
                np = np + 1
            end_p = find_matching_end(toks, np, 1)
            body = compile_class_body(toks, np, end_p - 1, name)
            return 列表创建("class " + name + ":\n" + body, end_p)
    return 列表创建("", p)

def compile_class_body(toks, p, end_p, class_name):
    out = ""
    while p < end_p and p < 列表长度(toks):
        tok = 列表获取(toks, p)
        tv = 列表获取(tok, 1)
        if tv == "属性":
            np = p + 1
            if np < 列表长度(toks):
                attr_tok = 列表获取(toks, np)
                attr_name = 列表获取(attr_tok, 1)
                p = np + 1
        if 是函数关键字(tv):
            func结果 = compile_class_method(toks, p, class_name)
            method_code = 列表获取(func结果, 0)
            p = 列表获取(func结果, 1)
            out = out + method_code
        if tv == "结束":
            return out
        p = p + 1
    return out

def compile_class_method(toks, p, class_name):
    tok = 列表获取(toks, p)
    np = p + 1
    name = ""
    if np < 列表长度(toks):
        name_tok = 列表获取(toks, np)
        name = 列表获取(name_tok, 1)
        np = np + 1
    参数结果 = 解析参数(toks, np)
    params = 列表获取(参数结果, 0)
    np = 列表获取(参数结果, 1)
    self_param = "self"
    if params != "":
        self_param = "self, " + params
    method_end = find_matching_end(toks, np, 1)
    body = compile_block(toks, np, method_end - 1, "        ", "")
    if body == "":
        body = "        pass"
    code = "    def " + name + "(" + self_param + "):\n" + body + "\n"
    return 列表创建(code, method_end)

def compile_top(toks, p, out):
    while p < 列表长度(toks):
        tok = 列表获取(toks, p)
        tv = 列表获取(tok, 1)
        已处理 = 假
        if tv == "类":
            结果 = compile_class(toks, p)
            class_code = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            out = out + class_code + "\n"
            p = np
            已处理 = 真
        if 已处理 == 假 and 是函数关键字(tv):
            结果 = compile_single_func(toks, p)
            func_code = 列表获取(结果, 0)
            np = 列表获取(结果, 1)
            out = out + func_code
            p = np
            已处理 = 真
        if 已处理 == 假:
            p = p + 1
    return out

def compile_single_func(toks, p):
    tok = 列表获取(toks, p)
    np = p + 1
    name = ""
    if np < 列表长度(toks):
        tok = 列表获取(toks, np)
        if 列表获取(tok, 0) == "ID":
            name = 列表获取(tok, 1)
            np = np + 1
    参数结果 = 解析参数(toks, np)
    params = 列表获取(参数结果, 0)
    np = 列表获取(参数结果, 1)
    body结果 = compile_stmts(toks, np, "")
    body = 列表获取(body结果, 0)
    np = 列表获取(body结果, 1)
    if body == "":
        body = "    pass\n"
    code = "def " + name + "(" + params + "):\n" + body + "\n"
    return 列表创建(code, np)

def 编译(src):
    header = "# Generated by Duan Level 3\n"
    toks = 词法(src)
    code = compile_top(toks, 0, "")
    return header + code

def 测试():
    src1 = "段落 foo 返回 42 结束"
    编译(src1)
    src2 = "段落 bar 设 x 为 10 返回 x 结束"
    编译(src2)
    src3 = "段落 baz 如果 真 返回 1 结束 返回 0 结束"
    编译(src3)

def 主函数():
    测试()

